name: eksi sozluk

on:
  schedule:
    # Her 180 dakikada calistir
    - cron: '*/180 * * * *'
    # Her gün gece saat 00:05'te çalıştır (UTC)
    - cron: '5 21 * * *'
    # Her gün saat 06:00'da çalıştır (UTC)
    - cron: '0 3 * * *'
  push:
    branches:
      - main  # Ana branch'ta değişiklik yapıldığında tetiklenecek
    paths:
      - '**/eksisozluk.yml'  # sadece 'eksisozluk.yml' dosyasındaki değişikliklerde tetiklenecek
  pull_request:
    branches:
      - main  # PR oluşturulduğunda tetiklenecek
    paths:
      - '**/eksisozluk.yml'  # sadece 'eksisozluk.yml' dosyasındaki değişikliklerde tetiklenecek

jobs:
  build:
    runs-on: ubuntu-latest  # Ubuntu ortamında çalışacak

    steps:
    - name: Check out code
      uses: actions/checkout@v2  # Kodunuzu checkout eder

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Python sürümünü belirleyin

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/workflows/requirements.txt  # Gereksinimlerinizi yükler

    - name: Run Eksi Sozluk script
      run: python auto_login.py  # Selenium scriptinizi çalıştırır

    - name: Clean up
      run: sudo apt-get remove -y chromium-browser # Tarayıcıyı temizler
